version: '3.4'

services:
  capstoneserver:
    image: capstoneserver
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3450:3450
