services:
  db:
    image: postgres:latest
    container_name: kome_db
    environment:
      POSTGRES_USER: komedb
      POSTGRES_PASSWORD: komepass7
      POSTGRES_DB: kome
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
